language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  - NODE_VERSION=4.2

install:
  - nvm install $NODE_VERSION
  - npm install macaca-cli macaca-electron -g

script:
  - nvm use $NODE_VERSION
  - make test
